*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*   generation date: 22.11.2012 at 18:14:05 by user DGOERKE
*   view maintenance generator version: #001407#
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZBOOK_TEAM_TMTOP.                 " Global Data
  INCLUDE LZBOOK_TEAM_TMUXX.                 " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZBOOK_TEAM_TMF00                       . " subprograms
  INCLUDE LZBOOK_TEAM_TMI00                       . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZBOOK_TEAM_TMF...                 " Subprograms
* INCLUDE LZBOOK_TEAM_TMO...                 " PBO-Modules
* INCLUDE LZBOOK_TEAM_TMI...                 " PAI-Modules
