REPORT zbook_simple_menu.

SELECTION-SCREEN BEGIN OF BLOCK a WITH FRAME TITLE text-tia.
SELECTION-SCREEN PUSHBUTTON /1(40) text-a01 USER-COMMAND a01.
SELECTION-SCREEN PUSHBUTTON /1(40) text-a02 USER-COMMAND a02.
SELECTION-SCREEN END OF BLOCK a.

AT SELECTION-SCREEN.
  CASE sy-ucomm.
    WHEN 'A01'.
      CALL FUNCTION 'VIEW_MAINTENANCE_CALL'
        EXPORTING
          action    = 'S'
          view_name = 'ZBOOK_AREAS'
        EXCEPTIONS
          OTHERS    = 15.
    WHEN 'A02'.
      CALL TRANSACTION 'ZBOOK_CLASS'.
  ENDCASE.
