*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*   generation date: 20.09.2012 at 16:36:35 by user EWULFF
*   view maintenance generator version: #001407#
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZBOOK_TPD01TOP.                   " Global Data
  INCLUDE LZBOOK_TPD01UXX.                   " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZBOOK_TPD01F00                         . " subprograms
  INCLUDE LZBOOK_TPD01I00                         . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZBOOK_TPD01F...                   " Subprograms
* INCLUDE LZBOOK_TPD01O...                   " PBO-Modules
* INCLUDE LZBOOK_TPD01I...                   " PAI-Modules

*INCLUDE LZBOOK_TPD01F01.

*INCLUDE LZBOOK_TPD01F02.

INCLUDE LZBOOK_TPD01F01.

INCLUDE LZBOOK_TPD01F02.

INCLUDE LZBOOK_TPD01F03.

INCLUDE LZBOOK_TPD01F04.

INCLUDE LZBOOK_TPD01F05.

INCLUDE LZBOOK_TPD01F06.
